# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7679253450e9a5c981f1b5364da22085ae2dba862926035b79e463f5a1b42fda5ab424d52682dbb5c25f8b27f196c6641b366ac639d15dcc0b4b931b2f1bec1e

test:
  secret_key_base: 4b494bd9d16d918ee29bcbdeea213509c13eb895843ed1e30480f119ded300dfb69ef6c1a188092f51c41c32079a9b277602dbdeb438a2605d431bd3603363fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
